name: Terraform ec2 deployment

on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan
      
      - name: terrafom apply
        run: terraform apply -auto-approve   

 